### ISSUE TITLE
1.18.2 Unable to enter world after failing to get version update information

### ISSUE THREAD

**Issue by TinyTsuki** [Edivad99/FluidSystem#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

EventHandler.handlePlayerLoggedInEvent() 中的
_VersionChecker.getResult()_ 获取失败(Status.FAILED)后调用
_versionRAW.changes()_ 导致异常, 修改后即可解决问题

EventHandler.handlePlayerLoggedInEvent() in
_VersionChecker.getResult()_ Called after a failed (Status.FAILED) acquisition
_versionRAW.changes()_ causes an exception, modify it to solve the problem
--Translated from DeepL

### How can I reproduce this bug or crash?

1. Use 1.18.2 to load the mod
2. Enter the world

### Configuration

```markdown
- Mod version:2.0.0
- Forge version:40.1.51
- Minecraft version:1.18.2
```

### Relevant log output

```shell
Error executing task on Client
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "net.minecraftforge.fml.VersionChecker$CheckResult.changes()" is null
	at edivad.fluidsystem.setup.EventHandler.handlePlayerLoggedInEvent(EventHandler.java:26) ~[%2381!/:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_81_EventHandler_handlePlayerLoggedInEvent_LoggedInEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.7.jar%239!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.7.jar%239!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.7.jar%239!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.firePlayerLogin(ForgeHooksClient.java:952) ~[forge-1.18.2-40.1.51_mapped_official_1.18.2-recomp.jar%2375%2382!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientPacketListener.handleLogin(ClientPacketListener.java:363) ~[forge-1.18.2-40.1.51_mapped_official_1.18.2-recomp.jar%2376!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.handle(ClientboundLoginPacket.java:45) ~[forge-1.18.2-40.1.51_mapped_official_1.18.2-recomp.jar%2376!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.handle(ClientboundLoginPacket.java:16) ~[forge-1.18.2-40.1.51_mapped_official_1.18.2-recomp.jar%2376!/:?] {re:classloading}
```

**Comment by Edivad99** [comment]
I released a new update with a file dedicated for 1.18.2
